language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required
    - python: "2.7"
      env: TOXENV=cov
      after_script: pip install --quiet coveralls && coveralls

branches:
  only:
    - master
    - develop

install: pip install tox tox-travis

script: tox
